### ISSUE TITLE
Implement image usage

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#326]
Adding Fig. for Monika colloquium here (yell at me in the comments if it's not a good practice and please let me know how to do it better)

Credit: C.Hohmann/MCQST
![LatticeGaugeZ2_Pressebild](https://user-images.githubusercontent.com/31961952/108638298-cd17d000-748e-11eb-86ae-4ea132c8654c.jpg)

**Comment by akhmerov** [comment]
Unfortunately I'm fully booked for a couple of days, and won't be able to work on this.

To outline my thoughts if someone (perhaps @everthemore) wants to take a look:

- We could manually upload the image to the repository
- To use it in the LRC page we would introduce an extra optional data field "image" in `talks.yml` which would contain the filename. The image credit would then go to the abstract, I guess.
- If an image is provided, we could use it in rendering the talk (although I'm not sure whether it would be easy to find a layout that would look good).

**Comment by everthemore** [comment]
For now, the image was meant for the announcement tweet mostly right? 
Why don't we simply respond to the LRC issue with the image, so that we have it in the right place? 
If then we decide to add it to talks.yml we can request that the issue responder comments with 'PR image' so that the bot knows that this is the image we want to use for the announcements (copying it to a separate folder perhaps, or just take it from there always).

**Comment by akhmerov** [comment]
Sounds good. Then in the short run let's add a checklist item:

```
- [ ] Cover image added to replies (or speaker doesn't have an image)
```

To the LRC template. Moving forward we will implement the more advanced features that you describe.
