### ISSUE TITLE
Email announcement: replication crisis in condensed matter

### ISSUE THREAD

**Issue by brianqskinner** [virtualscienceforum/virtualscienceforum#584]
subject: "Online workshop: replication crisis in condensed matter physics"
from: VSF team <no-reply@mail.virtualscienceforum.org>
to: vsf-announce 
---
Dear %recipient_name%,

We would like to announce an upcoming online workshop: "Does condensed matter physics need to worry about a replication crisis?" hosted by the Virtual Science Forum.
The workshop will take place on Thursday, March 2, from 12:00 to 3:00 US eastern time.

The goal of this short workshop is to review the causes and manifestations of the replication crisis as it is being experienced in the social and biomedical sciences, and then to consider whether the same issues apply to condensed matter physics. The workshop will include three talks: first an overview of the replication crisis in the social sciences and then talks that consider recent results in high-temperature superconductivity and the study of Majorana bound states. We conclude with a panel discussion.

Please visit the [workshop web page](https://virtualscienceforum.org/reproducibility_in_cmp/) to view the program of the workshop and to register.

Participation is free, but the number of participants is limited.

Thank you,  
the organizers: Brian Skinner and Sergey Frolov

**Comment by akhmerov** [comment]
I've published the workshop page for now without titles (will update once those are available). Would you like to send the announcement now?

I've also made minor changes:
- fixed the workshop URL
- stated that the workshop is hosted by the VSF so that recipients clearly understand why they are receiving the email.
- Reformatted the signature

Feel free to edit if you would like to change anything.

Ready to send when after a confirmation from you.

**Comment by brianqskinner** [comment]
It looks good to me. Please send the email announcement when you are ready.
